"use client";
import { useEffect, useState } from "react";
import { Sparkles, RefreshCw, AlertCircle } from "lucide-react";

export function OrgInsights({ orgId, orgName, accent }: { orgId: number; orgName: string; accent: string }) {
  const [data, setData] = useState<{ source: string; insights: string[] } | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  async function load() {
    setLoading(true);
    setError(null);
    try {
      const res = await fetch(`/api/organizations/${orgId}/insights`);
      if (!res.ok) throw new Error("Failed to load insights");
      const json = await res.json();
      setData({ source: json.source, insights: json.insights ?? [] });
    } catch (e) {
      setError(e instanceof Error ? e.message : "Error");
    } finally {
      setLoading(false);
    }
  }

  useEffect(() => { load(); /* eslint-disable-next-line react-hooks/exhaustive-deps */ }, [orgId]);

  return (
    <section className="rounded-lg border border-border bg-card p-4 space-y-3">
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-2">
          <Sparkles className="h-4 w-4" style={{ color: accent }} />
          <h2 className="text-sm font-semibold uppercase tracking-wider text-muted-foreground">AI Insights</h2>
        </div>
        <button onClick={load} disabled={loading} className="text-[10px] text-muted-foreground hover:text-foreground inline-flex items-center gap-1 disabled:opacity-50">
          <RefreshCw className={`h-3 w-3 ${loading ? "animate-spin" : ""}`} /> {loading ? "Analyzing…" : "Refresh"}
        </button>
      </div>

      {error ? (
        <div className="flex items-center gap-2 text-xs text-amber-600">
          <AlertCircle className="h-3.5 w-3.5" /> {error}
        </div>
      ) : loading ? (
        <div className="space-y-2">
          {[0, 1, 2].map((i) => <div key={i} className="h-3 rounded bg-muted animate-pulse" style={{ width: `${85 - i * 15}%` }} />)}
        </div>
      ) : data ? (
        <>
          <ul className="space-y-2">
            {data.insights.map((insight, i) => (
              <li key={i} className="flex items-start gap-2 text-xs leading-relaxed">
                <span className="mt-1 h-1.5 w-1.5 shrink-0 rounded-full" style={{ background: accent }} />
                <span>{insight}</span>
              </li>
            ))}
          </ul>
          <p className="text-[9px] text-muted-foreground">
            Generated by {data.source === "ai" ? "9jatruth AI" : "9jatruth analytics"} · based on {orgName}&apos;s activity data
          </p>
        </>
      ) : null}
    </section>
  );
}
