"use client";

import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { Brain, Loader2, RefreshCw, Sparkles } from "lucide-react";
import { EmergencyAgency } from "@/lib/emergency-agencies";
import { Button } from "@/components/ui/button";

export function AgencyAIBriefing({ agency }: { agency: EmergencyAgency }) {
  const [nonce, setNonce] = useState(0);
  const { data, isLoading, isFetching } = useQuery({
    queryKey: ["agency-briefing", agency.slug, nonce],
    queryFn: async () => {
      const res = await fetch(`/api/alerts/agency-briefing?slug=${agency.slug}`);
      if (!res.ok) throw new Error("failed");
      return res.json() as Promise<{ briefing: string; source: "ai" | "static"; steps: string[] }>;
    },
  });

  return (
    <div className="rounded-lg border border-violet-500/30 bg-violet-500/5 p-4 space-y-3">
      <div className="flex items-center justify-between gap-2">
        <div className="flex items-center gap-2">
          <div className="flex h-7 w-7 items-center justify-center rounded-md bg-violet-500/15">
            <Brain className="h-4 w-4 text-violet-500" />
          </div>
          <div>
            <h2 className="text-sm font-semibold">AI Safety Briefing</h2>
            <p className="text-[10px] text-muted-foreground">
              Context-aware guidance generated for {agency.shortName}
            </p>
          </div>
        </div>
        <Button
          size="sm"
          variant="ghost"
          className="h-7 gap-1 text-xs"
          disabled={isFetching}
          onClick={() => setNonce((n) => n + 1)}
        >
          <RefreshCw className={`h-3 w-3 ${isFetching ? "animate-spin" : ""}`} />
          Regenerate
        </Button>
      </div>

      {isLoading ? (
        <div className="flex items-center gap-2 text-xs text-muted-foreground py-2">
          <Loader2 className="h-3.5 w-3.5 animate-spin" /> Generating briefing…
        </div>
      ) : (
        <div className="space-y-3">
          <p className="text-xs text-foreground/90 leading-relaxed">{data?.briefing}</p>
          {data?.steps && data.steps.length > 0 && (
            <div className="space-y-1">
              <div className="flex items-center gap-1 text-[10px] uppercase tracking-wider text-muted-foreground font-semibold">
                <Sparkles className="h-2.5 w-2.5" /> Recommended actions
              </div>
              <ol className="space-y-1">
                {data.steps.map((s, i) => (
                  <li key={i} className="text-xs text-muted-foreground flex gap-2">
                    <span className="font-mono text-violet-500">{i + 1}.</span>
                    <span>{s}</span>
                  </li>
                ))}
              </ol>
            </div>
          )}
          <p className="text-[9px] text-muted-foreground">
            {data?.source === "ai" ? "Generated by AI — always use judgement in real emergencies." : "Standard guidance — AI model not configured."}
          </p>
        </div>
      )}
    </div>
  );
}
